dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: iHOB2MIzD15zfygHSa3B7ekVh/bvF43YqgLrXmdfhdP6NiKikCn7M4ABFlX1s3+edpSeIzZtPscYpumxMEww24CJFFi2/XyvhwZ5Mh/rkVWMlmrev+ePa2CWVI2NNzQ7T3DJuf6zN0cZCd3IuX/kh473NdGFboflLcJTjTGidcw949vzOWzN5CSfY0XKNgn43fi2xmi2QcVjVVn6hlXrQA2mL9dVuSOq+kOnC1lOCCLgeLn3H3SC7h3HMV6CLUCIFNruYzmmWzLLLsMAnyjx+KlfSq4Fzsr4p+0qqE+8sKpRgfL1LqryHh9Im2A07RijNytosTvXErHGAcY9VwoXiJp3lTA4NNcE7/6vE3jlxKqQCK0AYP1dlRFauAnoeecCFDQFrU9/eaxxIZErz28VlVk1XVAIFtoHt35YrkeYTUPVcaQK3H6F72Gi7J3/j7SoSA7LmBAvbVpDliYF/oBTsMCxG/1eWlGGmNeJeaJDgQXR94mRuDWZGgIiee1esgLtvCc+fEhQS7QRgmo6gujHlS7LRbnEU9KIZIh0QK9W64Snoel1XqAgfplwKzGBounE+QjmUYW/dFy0Ek++EZTjzpfmj55b88euEWoaXuduIUsVSV/5BXuFITPyRuRwLN4qBsb83ggt5RiQrvN5HPaVSG99sx2X0FVebwaQvs5WJOs=
