version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      back_net:
        aliases:
          - prometheus
      front_net:
        aliases:
          - prometheus

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
        aliases:
          - node-exporter
      front_net:
        aliases:
          - node-exporter

  mongodb-exporter:
    image: mirantisworkloads/mongodb-prometheus-exporter:1.0.0
    ports:
      - '9001:9001'
    environment:
      - MONGODB_URL=mongodb://post_db
    command:
      - ./mongodb_exporter
    networks:
      back_net:
        aliases:
          - mongodb-exporter
      front_net:
        aliases:
          - mongodb-exporter

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.12.0
    ports:
      - '9115:9115'
    networks:
      back_net:
        aliases:
          - blackbox-exporter
      front_net:
        aliases:
          - blackbox-exporter

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      back_net:
        aliases:
          - cadvisor

volumes:
  prometheus_data:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24

  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.0.1.0/24

