kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: tRkKY09XdU1u89P5PUdTroBjbEE0k9MzgmxVnsm/b7E=
      - identity: {}
